vich_uploader:
    db_driver: orm

    mappings:
        property_image:
           uri_prefix: /img/utilisateurs
           upload_destination: '%kernel.project_dir%/public/img/utilisateurs'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
